### ISSUE TITLE
DELETE endpoint returns 404

### ISSUE THREAD

**Issue by michaeltoohig** [awtkns/fastapi-crudrouter#95] opened 2021-09-13 10:41 UTC
I'm mixing this project and FastAPI-Users together so I have a very basic DatabasesCRUDRouter that has delete_all_route disabled and the delete_one_route has FastAPI-Users dependency for superuser on it. Otherwise, nothing else interacts with the delete endpoints yet when I delete an item I'm returned with 404 error and the detail says the item is not found.

The item is deleted though.

```python
from fastapi import Depends
from fastapi_crudrouter import DatabasesCRUDRouter

from app.core.users import fastapi_users
from app.db.session import database
from app.models.thing import Thing as ThingTable 
from app.schemas.thing import ThingCreate, Thing

current_active_verified_user = fastapi_users.current_user(active=True, verified=True)
current_superuser = fastapi_users.current_user(active=True, superuser=True)

thing_db = ThingTable.__table__

router = DatabasesCRUDRouter(
    prefix="things",
    tags=["things"],
    schema=Thing,
    create_schema=ThingCreate,
    table=thing_db,
    database=database,
    # Disable delete_all endpoint
    delete_all_route=False,
    # Dependencies for endpoints
    create_route=[Depends(current_active_verified_user)],
    update_route=[Depends(current_active_verified_user)],
    delete_one_route=[Depends(current_superuser)],
)
```

**Comment by awtkns** [comment] 2021-09-14 03:36
@michaeltoohig thanks for reporting this, would you be to provide me with a minable runnable example?

**Comment by awtkns** [comment] 2021-09-14 05:27
I added a test in #96 which disables the delete_all route while keeping the delete_one route enabled. It passes, I am thinking I could be due to something in your dependancy.

**Comment by michaeltoohig** [comment] 2021-09-14 08:10
Sorry, I didn't make a reproducible example earlier. Either way, I looked further into to confirm the issue is not the dependency. I tested by both removing the dependency all together and by overriding the endpoint.

```python
def _delete_one(self, *args: Any, **kwargs: Any) -> CALLABLE:
        async def route(item_id: self._pk_type) -> Model:  # type: ignore
            query = self.table.delete().where(self._pk_col == item_id)

            row = await self._get_one()(item_id)  # <--- here is the source of the 404
            rid = await self.db.execute(query=query)

            if rid:
                return row
            else:
                raise NOT_FOUND

        return route
```

In the `_delete_one` endpoint the above marked line is the point that raises the 404 HTTPException. I paused at the line before and in my database the row has already been removed. So now I need to look more into either my database config (standard postgres 13 docker image), or project config is committing the delete too early.

```python
database = databases.Database(settings.SQLALCHEMY_DATABASE_URI)
engine = create_engine(
    settings.SQLALCHEMY_DATABASE_URI,
    pool_pre_ping=True,
)
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
```

So I think the issue is `database` does not have `autoflush=False` or equivalent, which is used by the CRUDRouter. In a similar looking issue (I may be wrong) https://github.com/encode/databases/issues/219 the databases project passes blame down to `asyncpg`.

**Comment by awtkns** [comment] 2021-09-15 00:53
@michaeltoohig thanks for the detailed response, this certainly sounds like a bug, Assuming the `id` is in the database, it should be returned on the line `row = await self._get_one()(item_id)`. We do not even execute the delete till after, so this is certainly strange.

```python
async def route(item_id: self._pk_type) -> Model:  # type: ignore
  query = self.table.delete().where(self._pk_col == item_id)  # <--- Here we are just building the query to execute later
  
  row = await self._get_one()(item_id) <- getting the object
  rid = await self.db.execute(query=query)  # <--- The object get removed here
  
  if rid:
    return row
  else:
    raise NOT_FOUND
```

By chance do you have a single file that I could run to reproduce the issue? From there I may able to implement a fix.

**Comment by michaeltoohig** [comment] 2021-09-15 03:31
Here is a single file example. It does not cause the issue when tested with sqlite, just postgres. I included the fastapi-users setup as well since that's what I'm working with but I believe it can be ignored from my quick test commenting out code related to it but just in case I left it here.

```python
import databases
import sqlalchemy
from fastapi import FastAPI, Request
from fastapi_crudrouter import DatabasesCRUDRouter
from fastapi_users import FastAPIUsers, models
from fastapi_users.authentication import JWTAuthentication
from fastapi_users.db import SQLAlchemyBaseUserTable, SQLAlchemyUserDatabase
from sqlalchemy.ext.declarative import DeclarativeMeta, declarative_base
from sqlalchemy.orm import sessionmaker
from sqlalchemy import Column, Integer, String
from pydantic import BaseModel

DATABASE_URL = "postgresql://test:test@localhost/test"
SECRET = "SECRET"

app = FastAPI()


#
## SCHEMAS
#


class User(models.BaseUser):
    pass

class UserCreate(models.BaseUserCreate):
    pass

class UserUpdate(User, models.BaseUserUpdate):
    pass

class UserDB(User, models.BaseUserDB):
    pass


class ThingCreate(BaseModel):
    name: str

class Thing(ThingCreate):
    id: int


#
## PERSISTENCE
#


database = databases.Database(DATABASE_URL)
Base: DeclarativeMeta = declarative_base()


class UserTable(Base, SQLAlchemyBaseUserTable):
    pass

class ThingTable(Base):
    __tablename__ = 'things'
    id = Column(Integer, primary_key=True)
    name = Column(String, nullable=False)

engine = sqlalchemy.create_engine(DATABASE_URL, pool_pre_ping=True)
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
Base.metadata.create_all(engine)


#
## FASTAPI USERS
#


users = UserTable.__table__
user_db = SQLAlchemyUserDatabase(UserDB, database, users)


def on_after_register(user: UserDB, request: Request):
    print(f"User {user.id} has registered.")


def on_after_forgot_password(user: UserDB, token: str, request: Request):
    print(f"User {user.id} has forgot their password. Reset token: {token}")


def after_verification_request(user: UserDB, token: str, request: Request):
    print(f"Verification requested for user {user.id}. Verification token: {token}")


jwt_authentication = JWTAuthentication(
    secret=SECRET, lifetime_seconds=3600, tokenUrl="auth/jwt/login"
)


fastapi_users = FastAPIUsers(
    user_db,
    [jwt_authentication],
    User,
    UserCreate,
    UserUpdate,
    UserDB,
)
app.include_router(
    fastapi_users.get_auth_router(jwt_authentication), prefix="/auth/jwt", tags=["auth"]
)
app.include_router(
    fastapi_users.get_register_router(on_after_register), prefix="/auth", tags=["auth"]
)
app.include_router(
    fastapi_users.get_reset_password_router(
        SECRET, after_forgot_password=on_after_forgot_password
    ),
    prefix="/auth",
    tags=["auth"],
)
app.include_router(
    fastapi_users.get_verify_router(
        SECRET, after_verification_request=after_verification_request
    ),
    prefix="/auth",
    tags=["auth"],
)
app.include_router(fastapi_users.get_users_router(), prefix="/users", tags=["users"])


@app.on_event("startup")
async def startup():
    await database.connect()


@app.on_event("shutdown")
async def shutdown():
    await database.disconnect()


#
## FASTAPI CRUDROUTER
#


thing_router = DatabasesCRUDRouter(
    schema=Thing,
    create_schema=ThingCreate,
    table=ThingTable.__table__,
    database=database,
    delete_all_route=False,
)
app.include_router(thing_router)
```

**Comment by awtkns** [comment] 2021-09-15 05:08
Also mentioned here: https://github.com/kvesteri/sqlalchemy-continuum/issues/259

**Comment by awtkns** [comment] 2021-09-15 05:51
@michaeltoohig thanks for the code. I was able to get the tests failing. Hoping to implement the fetch and delete in separate transactions. This should resolve you issue.

**Comment by awtkns** [comment] 2021-09-16 06:50
@michaeltoohig after much digging, the issue has seemed to stem from this: https://github.com/tiangolo/fastapi/issues/1369 (answered here: https://github.com/tiangolo/fastapi/issues/1369#issuecomment-640254197). I am also not an expert on `encode/databases` but you maybe be also to fix it using this.

I am also implementing a fix for it natively in crudrouter. You can test out a sample of it with:
```bash
pip3 install wheel
pip3 install git+https://github.com/awtkns/fastapi-crudrouter.git@86_asyncpg_databases
```

Let me know if that works for you. 😄

**Comment by michaeltoohig** [comment] 2021-09-16 08:15
That does work, now I get the 200 response as expected.

Much appreciated!

**Comment by awtkns** [comment] 2021-09-16 15:49
Reopened until fix is merged.

**Closed** 2021-10-02 04:05 UTC
Labels: bug
